### ISSUE TITLE
this.currentStep is undefined

### ISSUE THREAD

**Issue by kmorales13** [tnicola/angular2-joyride#1]
Hi there.
Thanks for your library. I tried using it following the instructions in the readme but I was unable to get it working.

As per the title, I get a `this.currentStep is undefined` error at `JoyrideStepService.showCurrentStep`, which is called by `JoyrideStepService.startTour`.

Im guessing this part `this.currentStep = this.stepsContainerService.get(this.currentStepIndex);` is the one returning undefined?

My code:
```
<div class="branding" joyrideStep [stepNumber]="1">
    ...
</div>
<div class="header" joyrideStep [stepNumber]="2">
    ...
</div>
```

```
constructor(..., private joyride: JoyrideService) {
    ...
    this.joyride.startTour();
}
```

Maybe Im missing something 😁 cheers.

P.S. Im using angular 5

**Comment by tnicola** [comment]
Hi @kmorales13!Thanks to you for using the library, I'm sorry for the incovenience. Can I ask you something?Are your divs visible (in the DOM) when you try to start the Tour?

**Comment by rishikeshjadhav** [comment]
@kmorales13  
I followed the steps in README and was able to run this properly, few more details about your error would help.

**Comment by kmorales13** [comment]
Sorry for the late reply. Using the AfterViewInit hook works for me; the DOM elements were probably not ready as you mentioned. Thanks!

**Comment by ritik-tevathiya** [comment]
ngx-joyride.js:278 ngx-joyride:::Forcing the tour closure: First or Last step not found in the DOM 

can anyone send me reply
