### ISSUE TITLE
Facing issue with latest version "angular2-joyride": "^1.0.0"

### ISSUE THREAD

**Issue by rishikeshjadhav** [tnicola/angular2-joyride#2]
I followed steps in README with latest version, faced below issue,

calling this.joyrideService.startTour(); on click of a button.

Using Angular 5.

ERROR TypeError: Cannot read property 'targetViewContainer' of undefined
    at t.showCurrentStep (angular2-joyride.esm.js:formatted:1)
    at t.startTour (angular2-joyride.esm.js:formatted:1)
    at t.startTour (angular2-joyride.esm.js:formatted:1)
    at HomeComponent.onClick (home.component.ts:26)
    at Object.eval [as handleEvent] (HomeComponent.html:2)
    at handleEvent (core.js:13547)
    at callWithDebugContext (core.js:15056)
    at Object.debugHandleEvent [as handleEvent] (core.js:14643)
    at dispatchEvent (core.js:9962)
    at eval (core.js:10587)

--------------------------------------------------------------------------------

Note:
I was not facing this issue with version 0.0.5, @tnicola, need help on this.

**Comment by rishikeshjadhav** [comment]
@tnicola  Was able to resolve this issue.
I have a multi module project setup, due to which i had to import JoyrideService in the module inside which i was using the tour directive.

Closing the issue.

**Comment by B1ll1** [comment]
I'm facing the same problem here. No clue how to fix this.

**Comment by tnicola** [comment]
Hi @B1ll1 ,

Are you using the latest `ngx-joyride@2.0.1`? Are all your steps in the same page or are they shared across different routes / lazy loaded modules?

**Comment by B1ll1** [comment]
They are in the same page @tnicola, and yes I'm using the latest version

**Comment by tnicola** [comment]
Ok, don't worry. Thanks for the information. Are you using the @angular/router for navigating through your pages?

**Comment by B1ll1** [comment]
Yes, I'm using router but I will use this functionality only in one page for now.

**Comment by tnicola** [comment]
Is your `firstStep` on a particular route?

**Comment by B1ll1** [comment]
This first step will only be executed in an specific route but since it's only in one page do I need to add any route configuration?

**Comment by tnicola** [comment]
Yes, you do need it. If it's executed in a specific route then you should specify it, even if you're in the same page. 
e.g. your route is `my/special/route`, then you will have `steps: ['firstStep@my/special/route']`. The only case in which you should not specify any route is when your step is placed in the root (`/`).

**Comment by B1ll1** [comment]
Okay, I will try this, I have a complex routing module, a lot of parameters but I think this is going to work now. Thank you man, I will let you know about my progress :)

**Comment by tnicola** [comment]
@B1ll1 Yes, that one should work but only if your firstStep is really located under the route in which you're starting the tour. 

e.g. : You're calling `startTour({steps: [`firstStep@${this.router.url}`]})` in the MenuComponent and MenuComponent is located under the `routeA`. The result will be `startTour({steps: ["firstStep@routeA"]})`. So, if your step really is under `routeA` it will work but if your step is under `routeB` it won't work. 

I'm thinking to a solution but it's not so easy to handle routes with parameters.  For the moment you should know which your route exactly is at the beginning and you can't use a dynamic one.

**Comment by B1ll1** [comment]
Thank you for your help tnicola, I decided to implement something else to handle this case for the application.
